version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "deps(cargo)"
    # Ignore dependencies that have been intentionally removed during P2 cleanup
    ignore:
      - dependency-name: "serde*"
      - dependency-name: "tokio*" 
      - dependency-name: "tracing*"
      - dependency-name: "env_logger"
      - dependency-name: "log"
      - dependency-name: "once_cell"
      - dependency-name: "lazy_static"
      - dependency-name: "futures*"
      - dependency-name: "async-trait"

