version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "deps(cargo)"
    # 如需忽略某些依赖或限制大版本升级，可按需启用：
    # ignore:
    #   - dependency-name: "tracing*"
    #     update-types: ["version-update:semver-major"]

