[package]
name = "badbatch"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
authors = ["BadBatch Team"]
description = "High-Performance Disruptor Engine - A complete Rust implementation of the LMAX Disruptor pattern"
license = "AGPL-3.0"
repository = "https://github.com/deadjoe/badbatch"
keywords = ["disruptor", "lock-free", "high-performance", "messaging", "queue"]
categories = ["concurrency", "data-structures", "network-programming"]

[lib]
name = "badbatch"
path = "src/lib.rs"

[features]
default = []
shared-ring-buffer = []

[dependencies]
# Core dependencies
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
thiserror = "1.0"

# Configuration
env_logger = "0.10"

# Async runtime
uuid = { version = "1.0", features = ["v4", "serde"] }

# Synchronization primitives
parking_lot = "0.12"
crossbeam-utils = "0.8"
core_affinity = "0.8"
chrono = { version = "0.4.41", features = ["serde"] }

[dev-dependencies]
# Testing and benchmarking
criterion = { version = "0.5", features = ["html_reports", "async_tokio"] }
tokio-test = "0.4"
crossbeam = "0.8"  # For performance comparison benchmarks
proptest = "1.0"  # Property-based testing

# Benchmark configurations
[[bench]]
name = "spsc_benchmark"
harness = false

[[bench]]
name = "mpsc_benchmark"
harness = false

[[bench]]
name = "throughput_comparison"
harness = false

[[bench]]
name = "simple_benchmark"
harness = false

[profile.release]
# Optimize for performance
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
# Optimize benchmarks
opt-level = 3
lto = true
codegen-units = 1
debug = true
